import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/context/QueryProvider";
import NavBar from "@/components/NavBar";
import NextTopLoader from "nextjs-toploader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <QueryProvider>
          <NavBar />
          <NextTopLoader
            color="linear-gradient(to right, #b540f5, #a742f5, #9845f4, #8946f3, #7848f2)"
            showAtBottom={false}
          />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
//  <QueryProvider>
//         <NavBar />         {children}
//       </QueryProvider>